<?php

namespace App\Faker;

use Faker\Provider\Base;

class ProductProvider extends Base
{
    protected static array $productName = [
        'iPhone 9',
        'iPhone X',
        'Samsung Universe 9',
        'OPPOF19',
        'Huawei P30',
        'MacBook Pro',
        'Samsung Galaxy Book',
        'Microsoft Surface Laptop 4',
        'Infinix INBOOK',
        'HP Pavilion 15-DK1056WM',
        'perfume Oil',
        'Brown Perfume',
        'Fog Scent Xpressio Perfume',
        'Non-Alcoholic Concentrated Perfume Oil',
        'Eau De Perfume Spray',
        'Hyaluronic Acid Serum',
        'Tree Oil 30ml',
        'Oil Free Moisturizer 100ml',
        'Skin Beauty Serum.',
        'Freckle Treatment Cream- 15gm',
        '- Daal Masoor 500 grams',
        'Elbow Macaroni - 400 gm',
        'Orange Essence Food Flavou',
        'Cereals Muesli Fruit Nuts',
        'Gulab Powder 50 Gram',
        'Plant Hanger For Home',
        'Flying Wooden Bird',
        '3D Embellishment Art Lamp',
        'Handcraft Chinese style',
        'Key Holder',
        'Mornadi Velvet Bed',
        'Sofa for Coffe Cafe',
        '3 Tier Corner Shelves',
        'Plastic Table',
        '3 DOOR PORTABLE',
        'Sleeve Shirt Womens',
        'ank Tops for Womens/Girls',
        'sublimation plain kids tank',
        'Women Sweaters Wool',
        'women winter clothes',
        'NIGHT SUIT',
        'Stiched Kurta plus trouser',
        'frock gold printed',
        'Ladies Multicolored Dress',
        'Malai Maxi Dress',
        'Women\'s shoes',
        'Sneaker shoes',
        'Women Strip Heel',
        'Chappals & Shoe Ladies Metallic',
        'Women Shoes',
        'Half sleeves T shirts',
        'FREE FIRE T Shirt',
        'printed high quality T shirts',
        'Pubg Printed Graphic T-Shirt',
        'Money Heist Printed Summer T Shirts',
        'Sneakers Joggers Shoes',
        'Loafers for men',
        'formal offices shoes',
        'Spring and summershoes',
        'Stylish Casual Jeans Shoes',
        'Leather Straps Wristwatch',
        'Waterproof Leather Brand Watch',
        'Royal Blue Premium Watch',
        'Leather Strap Skeleton Watch',
        'Stainless Steel Wrist Watch',
        'Steel Analog Couple Watches',
        'Fashion Magnetic Wrist Watch',
        'Stylish Luxury Digital Watch',
        'Golden Watch Pearls Bracelet Watch',
        'Stainless Steel Women',
        'Women Shoulder Bags',
        'Handbag For Girls',
        'Fancy hand clutch',
        'Leather Hand Bag',
        'Seven Pocket Women Bag',
        'Silver Ring Set Women',
        'Rose Ring',
        'Rhinestone Korean Style Open Rings',
        'Elegant Female Pearl Earrings',
        'Chain Pin Tassel Earrings',
        'Round Silver Frame Sun Glasses',
        'Kabir Singh Square Sunglass',
        'Wiley X Night Vision Yellow Glasses',
        'Square Sunglasses',
        'LouisWill Men Sunglasses',
        'Bluetooth Aux',
        't Temperature Controller Incubator Controller',
        'TC Reusable Silicone Magic Washing Gloves',
        'Qualcomm original Car Charger',
        'Cycle Bike Glow',
        'Black Motorbike',
        'HOT SALE IN EUROPE electric racing motorcycle',
        'Automatic Motor Gas Motorcycles',
        'new arrivals Fashion motocross goggles',
        'Wholesale cargo lashing Belt',
        'lighting ceiling kitchen',
        'Metal Ceramic Flower',
        '3 lights lndenpant kitchen islang',
        'American Vintage Wood Pendant Light',
        'Crystal chandelier maria theresa for 12 light',
    ];

    protected static array $productDescription = [
        "An apple mobile which is nothing like apple",
        "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
        "Samsung's new variant which goes beyond Galaxy to the Universe",
        "OPPO F19 is officially announced on April 2021.",
        "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
        "MacBook Pro 2021 with mini-LED display may launch between September, November",
        "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
        "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
        "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
        "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
        "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
        "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
        "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
        "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
        "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
        "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
        "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
        "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
        "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
        "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
        "Fine quality Branded Product Keep in a cool and dry place",
        "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
        "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
        "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji",
        "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
        "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
        "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
        "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
        "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
        "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
        "Mornadi Velvet Bed Base with Headboard Slats Support Classic Style Bedroom Furniture Bed Set",
        "Ratttan Outdoor furniture Set Waterproof  Rattan Sofa for Coffe Cafe",
        "3 Tier Corner Shelves | 3 PCs Wall Mount Kitchen Shelf | Floating Bedroom Shelf",
        "V﻿ery good quality plastic table for multi purpose now in reasonable price",
        "Material: Stainless Steel and Fabric  Item Size: 110 cm x 45 cm x 175 cm Package Contents: 1 Storage Wardrobe",
        "Cotton Solid Color Professional Wear Sleeve Shirt Womens Work Blouses Wholesale Clothing Casual Plain Custom Top OEM Customized",
        "PACK OF 3 CAMISOLES ,VERY COMFORTABLE SOFT COTTON STUFF, COMFORTABLE IN ALL FOUR SEASONS",
        "sublimation plain kids tank tops wholesale",
        "2021 Custom Winter Fall Zebra Knit Crop Top Women Sweaters Wool Mohair Cos Customize Crew Neck Women' S Crop Top Sweater",
        "women winter clothes thick fleece hoodie top with sweat pantjogger women sweatsuit set joggers pants two piece pants set",
        "NIGHT SUIT RED MICKY MOUSE..  For Girls. Fantastic Suits.",
        "FABRIC: LILEIN CHEST: 21 LENGHT: 37 TROUSER: (38) :ARABIC LILEIN",
        "Ghazi fabric long frock gold printed ready to wear stitched collection (G992)",
        "This classy shirt for women gives you a gorgeous look on everyday wear and specially for semi-casual wears.",
        "Ready to wear, Unique design according to modern standard fashion, Best fitting ,Imported stuff",
        "Close: Lace, Style with bottom: Increased inside, Sole Material: Rubber",
        "Synthetic Leather Casual Sneaker shoes for Women/girls Sneakers For Women",
        "Features: Flip-flops, Mid Heel, Comfortable, Striped Heel, Antiskid, Striped",
        "Womens Chappals & Shoe Ladies Metallic Tong Thong Sandal Flat Summer 2020 Maasai Sandals",
        "2020 New Arrivals Genuine Leather Fashion Trend Platform Summer Women Shoes",
        "Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands",
        "quality and professional print - It doesn't just look high quality, it is high quality.",
        "Brand: vintage Apparel ,Export quality",
        "Product Description Features: 100% Ultra soft Polyester Jersey. Vibrant & colorful printing on front. Feels soft as cotton without ever cracking",
        "Fabric Jercy, Size: M & L Wear Stylish Dual Stiched",
        "Gender: Men , Colors: Same as DisplayedCondition: 100% Brand New",
        "Men Shoes - Loafers for men - Rubber Shoes - Nylon Shoes - Shoes for men - Moccassion - Pure Nylon (Rubber) Expot Quality.",
        "Pattern Type: Solid, Material: PU, Toe Shape: Pointed Toe ,Outsole Material: Rubber",
        "Comfortable stretch cloth, lightweight body; ,rubber sole, anti-skid wear;",
        "High Quality ,Stylish design ,Comfortable wear ,FAshion ,Durable",
        "Style:Sport ,Clasp:Buckles ,Water Resistance Depth:3Bar",
        "Watch Crown With Environmental IPS Bronze Electroplating; Display system of 12 hours",
        "Men Silver Chain Royal Blue Premium Watch Latest Analog Watch",
        "Leather Strap Skeleton Watch for Men - Stylish and Latest Design",
        "Stylish Watch For Man (Luxury) Classy Men's Stainless Steel Wrist Watch - Box Packed",
        "Elegant design, Stylish ,Unique & Trendy,Comfortable wear",
        "Buy this awesome  The product is originally manufactured by the company and it's a top selling product with a very reasonable",
        "Stylish Luxury Digital Watch For Girls / Women - Led Smart Ladies Watches For Girls",
        "Product details of Golden Watch Pearls Bracelet Watch For Girls - Golden Chain Ladies Bracelate Watch for Women",
        "Fashion Skmei 1830 Shell Dial Stainless Steel Women Wrist Watch Lady Bracelet Watch Quartz Watches Ladies",
        "LouisWill Women Shoulder Bags Long Clutches Cross Body Bags Phone Bags PU Leather Hand Bags Large Capacity Card Holders Zipper Coin Purses Fashion Crossbody Bags for Girls Ladies",
        "This fashion is designed to add a charming effect to your casual outfit. This Bag is made of synthetic leather.",
        "This fashion is designed to add a charming effect to your casual outfit. This Bag is made of synthetic leather.",
        "It features an attractive design that makes it a must have accessory in your collection. We sell different kind of bags for boys, kids, women, girls and also for unisex.",
        "Seven Pocket Women Bag Handbags Lady Shoulder Crossbody Bag Female Purse Seven Pocket Bag",
        "Jewelry Type:RingsCertificate Type:NonePlating:Silver PlatedShapeattern:noneStyle:CLASSICReligious",
        "Brand: The Greetings Flower Colour: RedRing Colour: GoldenSize: Adjustable",
        "Fashion Jewellery 3Pcs Adjustable Pearl Rhinestone Korean Style Open Rings For Women",
        "Elegant Female Pearl Earrings Set Zircon Pearl Earings Women Party Accessories 9 Pairs/Set",
        "Pair Of Ear Cuff Butterfly Long Chain Pin Tassel Earrings - Silver ( Long Life Quality Product)",
        "A pair of sunglasses can protect your eyes from being hurt. For car driving, vacation travel, outdoor activities, social gatherings,",
        "Orignal Metal Kabir Singh design 2020 Sunglasses Men Brand Designer Sun Glasses Kabir Singh Square Sunglass",
        "Wiley X Night Vision Yellow Glasses for Riders - Night Vision Anti Fog Driving Glasses - Free Night Glass Cover - Shield Eyes From Dust and Virus- For Night Sport Matches",
        "Fashion Oversized Square Sunglasses Retro Gradient Big Frame Sunglasses For Women One Piece Gafas Shade Mirror Clear Lens 17059",
        "LouisWill Men Sunglasses Polarized Sunglasses UV400 Sunglasses Day Night Dual Use Safety Driving Night Vision Eyewear AL-MG Frame Sun Glasses with Free Box for Drivers",
        "Bluetooth Aux Bluetooth Car Aux Car Bluetooth Transmitter Aux Audio Receiver Handfree Car Bluetooth Music Receiver Universal 3.5mm Streaming A2DP Wireless Auto AUX Audio Adapter With Mic For Phone MP3",
        "Both Heat and Cool Purpose, Temperature control range; -50 to +110, Temperature measurement accuracy; 0.1, Control accuracy; 0.1",
        "TC Reusable Silicone Magic Washing Gloves with Scrubber, Cleaning Brush Scrubber Gloves Heat Resistant Pair for Cleaning of Kitchen, Dishes, Vegetables and Fruits, Bathroom, Car Wash, Pet Care and Multipurpose",
        "best Quality CHarger , Highly Recommended to all best Quality CHarger , Highly Recommended to all",
        "Universal fitment and easy to install no special wires, can be easily installed and removed. Fits most standard tyre air stem valves of road, mountain bicycles, motocycles and cars.Bright led will turn on w",
        "Engine Type:Wet sump, Single Cylinder, Four Stroke, Two Valves, Air Cooled with SOHC (Single Over Head Cam) Chain Drive Bore & Stroke:47.0 x 49.5 MM",
        "HOT SALE IN EUROPE electric racing motorcycle electric motorcycle for sale adult electric motorcycles",
        "150cc 4-Stroke Motorcycle Automatic Motor Gas Motorcycles Scooter motorcycles 150cc scooter",
        "new arrivals Fashion motocross goggles motorcycle motocross racing motorcycle",
        "Wholesale cargo lashing Belt Tie Down end Ratchet strap customized strap 25mm motorcycle 1500kgs with rubber handle",
        "Wholesale slim hanging decorative kid room lighting ceiling kitchen chandeliers pendant light modern",
        "Metal Ceramic Flower Chandelier Home Lighting American Vintage Hanging Lighting Pendant Lamp",
        "3 lights lndenpant kitchen islang dining room pendant rice paper chandelier contemporary led pendant light modern chandelier",
        "American Vintage Wood Pendant Light Farmhouse Antique Hanging Lamp Lampara Colgante",
        "Crystal chandelier maria theresa for 12 light",
    ];

    public function productName(): string
    {
        return static::randomElement(static::$productName);
    }

    public function productDescription(): string
    {
        return static::randomElement(static::$productDescription);
    }
}
